### ISSUE TITLE
easyGBD信令是否支持TCP传输

### ISSUE THREAD

**Issue by remindA** [tsingsee/EasyGBD#2]
在软件设置界面可以选择传输协议是TCP或者UDP
1. 当选择UDP时信令通过UDP收发
2. 选择TCP时信令依然是通过UDP收发的
版本1.0.20.1210

**Comment by leo-09** [comment]
正在加TCP传输，也可以加我微信18855117272

**Comment by anyan131** [comment]
请问现在信令支持TCP传输了吗
