### ISSUE TITLE
easyGBD linux平台SDK

### ISSUE THREAD

**Issue by hosea118** [tsingsee/EasyGBD#3]
我看README里面说支持各个平台，但给出来的只有Android？

**Comment by xastra** [comment]
windows的呢？

**Comment by weizi-era** [comment]
没有linux平台的SDK吗？

**Comment by 240084173** [comment]
同问，linux平台SDK

**Comment by SwordTwelve** [comment]
可以编译linux&nbsp; arm的所有平台，需要提供下交叉编译链



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月9日(周三) 下午3:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [tsingsee/EasyGBD] easyGBD linux平台SDK (Issue #3)




 
我看README里面说支持各个平台，但给出来的只有Android？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hosea118** [comment]
Linaro Releases
<https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/>
  用这个可以编一个吗

SwordTwelve ***@***.***> 于2022年10月11日周二 16:10写道：

**Comment by leo-09** [comment]
加QQ2779005381,获取技术支持
